name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check notebook runs
      id: check-notebook-runs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check notebook runs
        setup-command: pip install -r requirements.txt -q
        command: jupyter nbconvert --to script Exercise_Intro_to_RAG.ipynb --stdout
          | python
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-NOTEBOOK-RUNS_RESULTS: "${{steps.check-notebook-runs.outputs.result}}"
      with:
        runners: check-notebook-runs
